import * as normalColor from "./normal";
import * as alphaColor from "./alpha";

export type TColor = {
    100: string;
    200: string;
    300: string;
    400: string;
    500: string;
    600: string;
    700: string;
    800: string;
    900: string;
    1000: string;
    1100: string;
    1200: string;
};

export const normalAmber = normalColor.rtAmber;
export const normalBlue = normalColor.rtBlue;
export const normalBronze = normalColor.rtBronze;
export const normalBrown = normalColor.rtBrown;
export const normalCrimson = normalColor.rtCrimson;
export const normalCyan = normalColor.rtCyan;
export const normalGold = normalColor.rtGold;
export const normalGrass = normalColor.rtGrass;
export const normalGreen = normalColor.rtGreen;
export const normalIris = normalColor.rtIris;
export const normalIndigo = normalColor.rtIndigo;
export const normalJade = normalColor.rtJade;
export const normalLime = normalColor.rtLime;
export const normalMint = normalColor.rtMint;
export const normalOlive = normalColor.rtOlive;
export const normalOrange = normalColor.rtOrange;
export const normalPink = normalColor.rtPink;
export const normalPlum = normalColor.rtPlum;
export const normalPurple = normalColor.rtPurple;
export const normalRed = normalColor.rtRed;
export const normalRuby = normalColor.rtRuby;
export const normalSage = normalColor.rtSage;
export const normalSand = normalColor.rtSand;
export const normalSlate = normalColor.rtSlate;
export const normalSky = normalColor.rtSky;
export const normalTeal = normalColor.rtTeal;
export const normalTomato = normalColor.rtTomato;
export const normalViolet = normalColor.rtViolet;
export const normalYellow = normalColor.rtYellow;

export const alphaAmber = alphaColor.rtAmber;
export const alphaBlue = alphaColor.rtBlue;
export const alphaBronze = alphaColor.rtBronze;
export const alphaBrown = alphaColor.rtBrown;
export const alphaCrimson = alphaColor.rtCrimson;
export const alphaCyan = alphaColor.rtCyan;
export const alphaGold = alphaColor.rtGold;
export const alphaGrass = alphaColor.rtGrass;
export const alphaGreen = alphaColor.rtGreen;
export const alphaIris = alphaColor.rtIris;
export const alphaIndigo = alphaColor.rtIndigo;
export const alphaJade = alphaColor.rtJade;
export const alphaLime = alphaColor.rtLime;
export const alphaMint = alphaColor.rtMint;
export const alphaOlive = alphaColor.rtOlive;
export const alphaOrange = alphaColor.rtOrange;
export const alphaPink = alphaColor.rtPink;
export const alphaPlum = alphaColor.rtPlum;
export const alphaPurple = alphaColor.rtPurple;
export const alphaRed = alphaColor.rtRed;
export const alphaRuby = alphaColor.rtRuby;
export const alphaSage = alphaColor.rtSage;
export const alphaSand = alphaColor.rtSand;
export const alphaSlate = alphaColor.rtSlate;
export const alphaSky = alphaColor.rtSky;
export const alphaTeal = alphaColor.rtTeal;
export const alphaTomato = alphaColor.rtTomato;
export const alphaViolet = alphaColor.rtViolet;
export const alphaYellow = alphaColor.rtYellow;
